### ISSUE TITLE
Code Origin

### ISSUE THREAD

**Issue by HydrelioxGitHub** [gplaza/domoticz-alfawise#1]
Hello,

Can you add a link to my repository in your code please ? To explain where your code come from and maybe have some people to enhance this.

Thank you.

**Comment by gplaza** [comment]
sure ! no problem ! and thx for your code is very useful ! i 'll add a readme with your git :)
sorry for that i'm very busy for the moment

**Comment by gplaza** [comment]
In reality, i can solve your famous TODO for read the state of the device ! But i don't have a lot of time for personal dev ...

**Comment by HydrelioxGitHub** [comment]
Thanks, it is already solved but I haven't published yet. Same no time problem here ! I hope I will release the new code sometime in february.
